name: Go

on:
  push:
    branches: [ main ]

jobs:

  Automated-test-and-code-analisys:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Get
        run: go get -t -v ./...

      - name: Get lint
        run: go get -u golang.org/x/lint/golint

      - name: Get Go Cyclo
        run: go get github.com/fzipp/gocyclo/cmd/gocyclo

      - name: Go Mod Tidy
        run: go mod tidy

      - name: Build
        run: go build -v ./pkg/parser

      - name: Test
        run: go test ./pkg/parser -coverprofile=coverage.txt -covermode=atomic

      - name: Coverage
        run: bash <(curl -s https://codecov.io/bash)

      - name: Check for Cyclomatic complexity
        run: gocyclo -over 15 ./pkg/parser

      - name: Check for lint problems
        run: golint -set_exit_status ./pkg/parser
